version: '3.7'
services:
  mongodb_container:
    container_name: mongodb_replica
    hostname: mongodb_replica
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
    volumes:
      # seeding scripts
      - ./.docker/mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb_replica_data:/data/db # Enable persistence of db
    ports:
      - 37017:27017
      - 27017:27017
volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb_replica_data:
